WebApplication2/Controllers/WorksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
  public class WorksController : Controller
  {
    private readonly ApplicationContext _context;

    public WorksController(ApplicationContext context)
    {
      _context = context;
    }

    // GET: Works
    public async Task<IActionResult> Index()
    {
      return _context.Works != null ?
                  View(await _context.Works.ToListAsync()) :
                  Problem("Пока нету пройзведени");
    }

    // GET: Works/Details/5
    public async Task<IActionResult> Details(int? id)
    {
      if (id == null || _context.Works == null)
      {
        return NotFound();
      }

      var work = await _context.Works
          .FirstOrDefaultAsync(m => m.Id == id);
      if (work == null)
      {
        return NotFound();
      }

      return View(work);
    }
    
    public async Task<IActionResult> GetUsersWorks(int? id)
    {
      return _context.Works.Where(x => x.UserId == id) != null ?
        View(await _context.Works.Where(x => x.UserId == id).ToListAsync()) :
        Ok("У вас пока нету свойх пройзведени.");
    }
    // GET: Works/Create
    public IActionResult Create()
    {
      return View();
    }

    // POST: Works/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Title,Genre,PublicationDate,Rating,UserId")] Work work)
    {
      if (ModelState.IsValid)
      {
        _context.Add(work);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
      }
      return View(work);
    }

    // GET: Works/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
      if (id == null || _context.Works == null)
      {
        return NotFound();
      }

      var work = await _context.Works.FindAsync(id);
      if (work == null)
      {
        return NotFound();
      }
      return View(work);
    }

    // POST: Works/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Genre,PublicationDate,Rating,UserId")] Work work)
    {
      if (id != work.Id)
      {
        return NotFound();
      }

      if (ModelState.IsValid)
      {
        try
        {
          _context.Update(work);
          await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
          if (!WorkExists(work.Id))
          {
            return NotFound();
          }
          else
          {
            throw;
          }
        }
        return RedirectToAction(nameof(Index));
      }
      return View(work);
    }

    // GET: Works/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
      if (id == null || _context.Works == null)
      {
        return NotFound();
      }

      var work = await _context.Works
          .FirstOrDefaultAsync(m => m.Id == id);
      if (work == null)
      {
        return NotFound();
      }

      return View(work);
    }

    // POST: Works/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      if (_context.Works == null)
      {
        return Problem("Entity set 'ApplicationContext.Works'  is null.");
      }
      var work = await _context.Works.FindAsync(id);
      if (work != null)
      {
        _context.Works.Remove(work);
      }

      await _context.SaveChangesAsync();
      return RedirectToAction(nameof(Index));
    }

    private bool WorkExists(int id)
    {
      return (_context.Works?.Any(e => e.Id == id)).GetValueOrDefault();
    }
  }
}

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Works" asp-action="Index">Все произведения</a>
                        </li>
                        @((User.IsInRole("user")) ? "<li class='nav-item'><a class='nav-link text-dark' asp-area='' asp-controller='Works' asp-action='GetUsersWorks'>Мой произведения</a></li>" : "")
                        @((User.IsInRole("admin")) ? "<li class='nav-item'><a class='nav-link text-dark' asp-area='' asp-controller='User' asp-action='Index'>Пользователи</a></li><li class='nav-item'><a class='nav-link text-dark' asp-area='' asp-controller='Role' asp-action='Index'>Роли</a></li>" : "")
                    </ul>
                </div>
            </div>
            <div>
                @if (User.Identity.IsAuthenticated)
                {
                    <p>@User.Identity.Name</p>

                    <form method="post" asp-controller="Account" asp-action="Logout">
                        <input type="submit" value="Выход" />
                    </form>
                }
                else
                {
                    <a asp-controller="Account" asp-action="Login">Вход</a>
                    <a asp-controller="Account" asp-action="Register">Регистрация</a>
                }
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>